export const APPLE_CATEGORIES = [
  { value: '', label: '전체' },
  { value: '6014', label: '게임 전체', group: '게임' },
  { value: '7001', label: '액션', group: '게임' },
  { value: '7002', label: '어드벤처', group: '게임' },
  { value: '7003', label: '아케이드', group: '게임' },
  { value: '7004', label: '보드', group: '게임' },
  { value: '7005', label: '카드', group: '게임' },
  { value: '7006', label: '카지노', group: '게임' },
  { value: '7009', label: '가족', group: '게임' },
  { value: '7011', label: '음악', group: '게임' },
  { value: '7012', label: '퍼즐', group: '게임' },
  { value: '7013', label: '레이싱', group: '게임' },
  { value: '7014', label: '롤플레잉', group: '게임' },
  { value: '7015', label: '시뮬레이션', group: '게임' },
  { value: '7016', label: '스포츠', group: '게임' },
  { value: '7017', label: '전략', group: '게임' },
  { value: '7018', label: '퀴즈', group: '게임' },
  { value: '7019', label: '단어', group: '게임' },
  { value: '6000', label: '비즈니스', group: '앱' },
  { value: '6001', label: '날씨', group: '앱' },
  { value: '6002', label: '유틸리티', group: '앱' },
  { value: '6003', label: '여행', group: '앱' },
  { value: '6004', label: '스포츠', group: '앱' },
  { value: '6005', label: '소셜 네트워킹', group: '앱' },
  { value: '6006', label: '참고', group: '앱' },
  { value: '6007', label: '생산성', group: '앱' },
  { value: '6008', label: '사진 및 비디오', group: '앱' },
  { value: '6009', label: '뉴스', group: '앱' },
  { value: '6010', label: '내비게이션', group: '앱' },
  { value: '6011', label: '음악', group: '앱' },
  { value: '6012', label: '라이프스타일', group: '앱' },
  { value: '6013', label: '건강 및 피트니스', group: '앱' },
  { value: '6015', label: '금융', group: '앱' },
  { value: '6016', label: '엔터테인먼트', group: '앱' },
  { value: '6017', label: '교육', group: '앱' },
  { value: '6018', label: '도서', group: '앱' },
  { value: '6020', label: '의학', group: '앱' },
  { value: '6021', label: '잡지 및 신문', group: '앱' },
  { value: '6023', label: '음식 및 음료', group: '앱' },
  { value: '6024', label: '쇼핑', group: '앱' },
  { value: '6026', label: '개발자 도구', group: '앱' },
  { value: '6027', label: '그래픽 및 디자인', group: '앱' },
];
